Add IdentityCredential to Credential Type Registry
w3c/webappsec-credential-management pull request #201
Opened 2022-07-07 21:24 UTC by npm1

Fixes https://github.com/fedidcg/FedCM/issues/301

2022-07-08 12:33 UTC, johannhof requested changes
Had a few comments. Personally I'm not a fan of whitespace-cleanup on unrelated lines but I'll leave that to the editor's preference. :)

Note that I think I'll want to defer merging to @nsatragno as editor. It seems like this can wait until she's back, right?

2022-07-08 12:35 UTC, johannhof approved these changes
Sorry, meant to approve but let's wait on Nina.

2022-07-08 13:44 UTC, npm1 reviewed
Ah yea I didn't get rid of the whitespaces on purpose, my editor did that automatically heh... There was a lot of them! So I remade the patch to be only the specific change on the title.

2022-07-08 13:44 UTC, npm1 commented on index.bs
> +    "href": "https://github.com/fedidcg/FedCM",
Yea probably! I just copied the syntax from WEB-LOGIN, which seems incorrect.

2022-07-08 13:44 UTC, npm1 commented on index.bs
> +        <td><a href="https://www.w3.org/community/fed-id/">W3C</a></td>
I am following the example from the above which says W3C even though it links to WebAppSec specifically... Not sure either!

2022-07-12 19:35 UTC, johannhof commented on index.bs
> +        <td><a href="https://www.w3.org/community/fed-id/">W3C</a></td>
I don't think this is super important but I have a slight preference for FedID CG given that the spec says WebAppSec will "notify the requestor" for updates, so more precise seems better. We'll just have to update this once it moves out of incubation...

2022-07-29 14:51 UTC, nsatragno approved these changes
LGTM

Thank you @johannhof for the first review!

2022-07-29 14:51 UTC, merged